// GET /api/players/[id]/digest
//
// Returns an AI-generated daily outlook for the player.
// Generated by Claude claude-haiku-4-5-20251001 (fast + cheap).
// Cached in Supabase player_digests table — regenerated at most once per 24h.
// Falls back to a stat-based template if ANTHROPIC_API_KEY is not set.

import { NextRequest, NextResponse } from 'next/server';
import { serverSupa } from '@/lib/supabase';
import { getApprovedAppUser, unauth } from '@/lib/auth';
export const dynamic  = 'force-dynamic';
export const maxDuration = 30;

const DIGEST_TTL_MS = 24 * 60 * 60 * 1000;

function templateDigest(player: any): string {
  const price  = Number(player.current_price).toFixed(2);
  const fv     = Number(player.fair_value || player.expected_final_value || 0).toFixed(2);
  const ppg    = Number(player.ppg  || 0).toFixed(1);
  const apg    = Number(player.apg  || 0).toFixed(1);
  const rpg    = Number(player.rpg  || 0).toFixed(1);
  const gp     = Number(player.games_played || 0);
  const pctOfSeason = ((gp / 82) * 100).toFixed(0);
  const premium    = ((Number(player.current_price) / Number(player.fair_value || player.current_price) - 1) * 100).toFixed(1);
  const direction  = Number(premium) > 0 ? 'above' : 'below';
  const injury     = player.injury_status;

  return [
    `${player.name} is ${gp} games into the season (${pctOfSeason}% complete), averaging ${ppg} PPG, ${rpg} RPG, and ${apg} APG.`,
    `Current share price is $${price}, trading ${Math.abs(Number(premium))}% ${direction} the model's fair value of $${fv}.`,
    injury ? `⚠️ Injury note: currently listed as ${injury}${player.injury_description ? ` (${player.injury_description})` : ''}. Monitor status before trading.` : null,
    Number(premium) > 5
      ? `Shares appear slightly stretched relative to fundamentals — price may drift down toward fair value between games.`
      : Number(premium) < -5
      ? `Shares trading at a discount to fair value — upside if current stat pace holds through the rest of the season.`
      : `Shares are fairly valued relative to current season pace.`,
    `Settlement is June 15, 2026. At current pace, the model projects a final value near $${fv}.`,
  ].filter(Boolean).join(' ');
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } },
) {
  const user = await getApprovedAppUser(req);
  if (!user) return unauth();

  const { id } = params;
  const db = serverSupa();

  // Check cache
  const { data: cached } = await db
    .from('player_digests')
    .select('digest, generated_at')
    .eq('player_id', id)
    .maybeSingle();

  if (cached && Date.now() - new Date(cached.generated_at).getTime() < DIGEST_TTL_MS) {
    return NextResponse.json({ digest: cached.digest, cached: true });
  }

  // Load player
  const { data: player } = await db
    .from('players').select('*').eq('id', id).single();
  if (!player) return NextResponse.json({ digest: null });

  // Generate with Claude if key is available
  const apiKey = process.env.ANTHROPIC_API_KEY;
  let digest: string;

  if (apiKey) {
    try {
      const today = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
      const prompt = `You are a concise NBA analyst writing a daily player outlook for a sports trading app. Today is ${today}.

Player: ${player.name} (${player.position}, ${player.team})
Season stats: ${Number(player.ppg).toFixed(1)} PPG, ${Number(player.rpg).toFixed(1)} RPG, ${Number(player.apg).toFixed(1)} APG, ${Number(player.efficiency).toFixed(1)} EFF
Games played: ${player.games_played} of 82
Current share price: $${Number(player.current_price).toFixed(2)}
Model fair value: $${Number(player.fair_value || player.expected_final_value).toFixed(2)}
Injury status: ${player.injury_status || 'Healthy'}${player.injury_description ? ` — ${player.injury_description}` : ''}
24h price change: ${Number(player.price_change_pct_24h || 0).toFixed(2)}%

Write a 3–4 sentence performance outlook. Cover: current form, injury considerations if any, and whether the share price looks attractive vs fair value. Be direct and specific. No fluff, no disclaimers. Plain text only, no markdown.`;

      const response = await fetch('https://api.anthropic.com/v1/messages', {
        method:  'POST',
        headers: {
          'x-api-key':         apiKey,
          'anthropic-version': '2023-06-01',
          'content-type':      'application/json',
        },
        body: JSON.stringify({
          model:      'claude-haiku-4-5-20251001',
          max_tokens: 200,
          messages:   [{ role: 'user', content: prompt }],
        }),
        signal: AbortSignal.timeout(15000),
      });

      if (response.ok) {
        const data = await response.json();
        digest = data.content?.[0]?.text?.trim() ?? templateDigest(player);
      } else {
        digest = templateDigest(player);
      }
    } catch {
      digest = templateDigest(player);
    }
  } else {
    digest = templateDigest(player);
  }

  // Upsert into cache
  await db.from('player_digests').upsert(
    { player_id: id, digest, generated_at: new Date().toISOString() },
    { onConflict: 'player_id' },
  );

  return NextResponse.json({ digest, cached: false });
}
